version: '3.8'

services:
  server:
    image: auto-instrumentation-server
    ports:
      - "8080:8080"
    environment:
      - OTEL_TRACES_EXPORTER=console,otlp
      - OTEL_METRICS_EXPORTER=console
      - OTEL_SERVICE_NAME=ServerApp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317      

  client:
    image: auto-instrumentation-client
    depends_on:
      - server
    environment:
      - OTEL_TRACES_EXPORTER=console,otlp
      - OTEL_METRICS_EXPORTER=console
      - OTEL_SERVICE_NAME=ClientApp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - SERVER_URL=http://server:8080

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"            
    environment:
      - COLLECTOR_OTLP_ENABLED=true